language: go

sudo: false
dist: trusty
go: 1.11.x

notifications:
  email: false

before_script:
    - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)

script:
    - test -z $(gofmt -s -l $GO_FILES)
    - make test
    - make build
