[author]
name = "fristonio"						# Name of the challenge creator
email = "fristonio@protonmail.com"		# Email for contact
ssh_key = "ssh-rsa AAAAB3NzaC1y"		# Public SSH key for the challenge author

[challenge.metadata]
name = "simple-web"
flag = "BACKDOOR{SAMPLE_WEB_FLAG}"
type = "web:php:7.1:cli"

[challenge.env]
ports = [10002]
web_root = "challenge"
default_port = 10002
