# [fristonio] $ ~/.beast 
# ❮❮ tree
# .
# ├── auth_file
# ├── beast.db
# ├── config.toml
# └── .static.beast.htpasswd
# ├── remote/
# │   └── hack-test
# ├── secrets/
# │   ├── key.priv
# │   └── key.pub
# └── staging/
#
# Sample snapshot of .beast directory.
# Make sure the hack-test is a valid git directory
# Make sure you provide a valid existing authorized_keys_file
# Make sure key.pub is added to the deployed keys of the beast remote repo

authorized_keys_file = "/home/fristonio/.beast/auth_file"
scripts_dir = "/home/fristonio/.beast/scripts"
allowed_base_images = ["ubuntu:18.04", "ubuntu:16.04", "debian:jessie"]
jwt_secret = "beast"
slack_webhook = ""

[remote]
url = "git@github.com:sdslabs/hack-test.git"
name = "hack-test"
branch = "master"
ssh_key = "/home/fristonio/.beast/secrets/key.priv"
